name: Report an issue
description: Report a bug or unexpected behavior
title: "[Issue] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      placeholder: Describe the issue clearly
    validations:
      required: true
